### PR TITLE
fix usage of deprecated isnanf

### PR DESCRIPTION
**Pull request by rofl0r**
fixes build with musl libc

### CODE REVIEW

**Comment by keith-packard** [comment]
isnan takes a double, isnanf takes a float. I don't want to coerce to a double for this test. If musl is missing this function, then perhaps a musl-specific patch is required?

**Comment by rofl0r** [comment]
oh, i wasn't aware of that and came recently across https://github.com/godotengine/godot/issues/20036#issuecomment-403301627

it seems musl's isnan is a macro with 2 different codepaths for float and double
```c
#define isnan(x) ( \
        sizeof(x) == sizeof(float) ? (__FLOAT_BITS(x) & 0x7fffffff) > 0x7f800000 : \
        sizeof(x) == sizeof(double) ? (__DOUBLE_BITS(x) & -1ULL>>1) > 0x7ffULL<<52 : \
        __fpclassifyl(x) == FP_NAN)
```
whereas glibc defines it to use a GCC builtin:
```
./math/math.h:#  define isnan(x) __builtin_isnan (x)
```
the posix text is kinda odd:
```
     int isnan(real-floating x);
...
     The  isnan()  macro  shall determine whether its argument value is a NaN.
     First, an argument represented in a format wider than its  semantic  type
     is  converted  to  its semantic type.  Then determination is based on the
     type of the argument.
```
from my reading it appears as if it is intended to be type-agnostic.
but i'm unsure about how newlib, in which you are probably interested, is implementing it.
is there a difference in the compiled binary with isnanf vs isnan ?

**Comment by keith-packard** [comment]
I just tried using isnan instead of isnanf -- the resulting binary is 30 bytes larger. That's because gcclib implements isnan using for floats using __unordff2, which tests two floats to see if they are unordered (and hence one or both are NaNs), while isnanf only tests a single number and is hence much shorter.

So, I'd like to continue using isnanf for newlib platforms, which seems more relevant than musl given goals of this project target smaller systems than musl typically is used for.

So, that means using the 'isnanf' name so that we can make sure we have a version optimized for 32-bit floats. For musl, I suggest what you probably want is to include a #define isnanf(x) isnan(x) in your own project so that it will build correctly.

**Comment by rofl0r** [comment]
fair enough.

**Pull request closed without merging**
